'use client'

import { useEffect, useState, useRef } from 'react'
import { Button } from '@workspace/ui/components/button'
import {
  Sheet,
  SheetContent,
} from '@workspace/ui/components/sheet'
import { Loader2, Sparkles, RefreshCw } from 'lucide-react'
import { toast } from 'sonner'
import type { SuggestedPrompt } from './types'
import { cn } from '@workspace/common/lib'

// ============================================================
// Types
// ============================================================

interface SuggestionsSheetProps {
  projectId: string
  isOpen: boolean
  onOpenChange: (open: boolean) => void
  onSelectSuggestion: (suggestion: SuggestedPrompt) => void
}

interface SuggestionItem {
  id: string
  title: string
  prompt: string
  category: string | null
  isUsed: boolean
}

// ============================================================
// Category Badge Component
// ============================================================

function CategoryBadge({ category }: { category: string | null }) {
  if (!category) return null

  const categoryColors: Record<string, string> = {
    competitor: 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400',
    feature: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
    'how-to': 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
    local: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400',
    'buying-intent': 'bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-400',
    comparison: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400',
    'problem-solution': 'bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-400',
  }

  return (
    <span className={cn(
      'text-xs px-2 py-0.5 rounded-full font-medium capitalize',
      categoryColors[category] || 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300'
    )}>
      {category.replace('-', ' ')}
    </span>
  )
}

// ============================================================
// Suggestions Sheet Component
// ============================================================

export function SuggestionsSheet({
  projectId,
  isOpen,
  onOpenChange,
  onSelectSuggestion,
}: SuggestionsSheetProps) {
  const [suggestions, setSuggestions] = useState<SuggestionItem[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [canGenerate, setCanGenerate] = useState(true)
  const [remaining, setRemaining] = useState(100)
  const [usingSuggestionId, setUsingSuggestionId] = useState<string | null>(null)

  // Track if we've already triggered auto-generation
  const hasAutoGenerated = useRef(false)

  // ============================================================
  // Mock Data
  // ============================================================
  const mockSuggestions: SuggestionItem[] = [
    {
      id: 'sug-1',
      title: 'Best Project Management Tools',
      prompt: 'What are the best project management tools for remote teams in 2024?',
      category: 'comparison',
      isUsed: false,
    },
    {
      id: 'sug-2',
      title: 'How to Improve Productivity',
      prompt: 'How can I improve my team\'s productivity when working remotely?',
      category: 'how-to',
      isUsed: false,
    },
    {
      id: 'sug-3',
      title: 'CRM Solutions Comparison',
      prompt: 'What are the top CRM solutions for small businesses?',
      category: 'comparison',
      isUsed: false,
    },
    {
      id: 'sug-4',
      title: 'Marketing Automation Guide',
      prompt: 'How do I set up marketing automation for my e-commerce business?',
      category: 'how-to',
      isUsed: false,
    },
    {
      id: 'sug-5',
      title: 'Competitor Analysis',
      prompt: 'How does [Your Product] compare to competitors in the market?',
      category: 'competitor',
      isUsed: false,
    },
  ]

  // ============================================================
  // Load Suggestions
  // ============================================================

  const loadSuggestions = () => {
    if (!projectId) return
    setIsLoading(true)
    // Simulate loading suggestions
    setTimeout(() => {
      setSuggestions(mockSuggestions)
      setCanGenerate(true)
      setRemaining(95)
      setIsLoading(false)
    }, 500)
  }

  // ============================================================
  // Generate Suggestions
  // ============================================================

  const handleGenerate = () => {
    if (!canGenerate) {
      toast.error('Organization has reached the suggestion limit')
      return
    }
    setIsGenerating(true)
    toast.success('Generating suggestions...', {
      description: 'This may take a few seconds',
    })
    
    // Simulate generating new suggestions
    setTimeout(() => {
      const newSuggestions: SuggestionItem[] = [
        {
          id: `sug-${Date.now()}-1`,
          title: 'AI Integration Best Practices',
          prompt: 'What are the best practices for integrating AI into existing workflows?',
          category: 'how-to',
          isUsed: false,
        },
        {
          id: `sug-${Date.now()}-2`,
          title: 'Local Business Solutions',
          prompt: 'What are the best software solutions for local businesses?',
          category: 'local',
          isUsed: false,
        },
        {
          id: `sug-${Date.now()}-3`,
          title: 'Buying Guide',
          prompt: 'What should I consider when buying enterprise software?',
          category: 'buying-intent',
          isUsed: false,
        },
      ]
      setSuggestions((prev) => [...newSuggestions, ...prev])
      setRemaining((prev) => Math.max(0, prev - 3))
      setIsGenerating(false)
    }, 2000)
  }

  // Load suggestions when sheet opens
  useEffect(() => {
    if (isOpen && projectId) {
      hasAutoGenerated.current = false // Reset auto-generation flag
      loadSuggestions()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, projectId])

  // Auto-generate if no suggestions exist (after initial load)
  useEffect(() => {
    if (
      isOpen &&
      !isLoading &&
      suggestions.length === 0 &&
      canGenerate &&
      !isGenerating &&
      !hasAutoGenerated.current
    ) {
      hasAutoGenerated.current = true
      // Small delay to avoid triggering on rapid open/close
      const timer = setTimeout(() => {
        handleGenerate()
      }, 500)
      return () => clearTimeout(timer)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, isLoading, suggestions.length, canGenerate, isGenerating])

  // ============================================================
  // Handlers
  // ============================================================

  const handleSelectSuggestion = (suggestion: SuggestionItem) => {
    if (suggestion.isUsed) {
      toast.info('This suggestion has already been used')
      return
    }
    setUsingSuggestionId(suggestion.id)
    
    // Simulate using the suggestion
    setTimeout(() => {
      // Update local state to mark as used
      setSuggestions((prev) =>
        prev.map((s) =>
          s.id === suggestion.id ? { ...s, isUsed: true } : s
        )
      )

      // Call the callback with the suggestion
      onSelectSuggestion({
        id: suggestion.id,
        title: suggestion.title,
        prompt: suggestion.prompt,
        category: suggestion.category,
        isUsed: true,
      })

      toast.success('Prompt added to tracking')
      setUsingSuggestionId(null)
      onOpenChange(false)
    }, 500)
  }

  // ============================================================
  // Render
  // ============================================================

  const unusedSuggestions = suggestions.filter((s) => !s.isUsed)

  return (
    <Sheet open={isOpen} onOpenChange={onOpenChange}>
      <SheetContent className="w-full sm:max-w-[540px] p-0 flex flex-col">
        <div className="flex flex-col gap-y-6 px-8 py-10 flex-1 overflow-hidden">
          {/* Header */}
          <div className="flex items-start justify-between">
            <div>
              <h2 className="text-lg font-medium">Prompt Suggestions</h2>
              <p className="text-sm text-muted-foreground mt-1">
                AI-generated prompts based on your project context
              </p>
            </div>
            {canGenerate && (
              <Button
                variant="outline"
                size="sm"
                onClick={handleGenerate}
                disabled={isGenerating || isLoading}
                className="shrink-0"
              >
                {isGenerating ? (
                  <Loader2 className="h-4 w-4 animate-spin mr-2" />
                ) : (
                  <RefreshCw className="h-4 w-4 mr-2" />
                )}
                Generate More
              </Button>
            )}
          </div>

          {/* Remaining Count */}
          {remaining < 100 && (
            <p className="text-xs text-muted-foreground">
              {remaining} suggestions remaining for your organization
            </p>
          )}

          {/* Loading State */}
          {isLoading && (
            <div className="flex flex-col items-center justify-center py-12 gap-3">
              <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
              <p className="text-sm text-muted-foreground">Loading suggestions...</p>
            </div>
          )}

          {/* Generating State */}
          {!isLoading && isGenerating && suggestions.length === 0 && (
            <div className="flex flex-col items-center justify-center py-12 gap-3">
              <Sparkles className="h-8 w-8 animate-pulse text-blue-500" />
              <p className="text-sm text-muted-foreground">Generating AI suggestions...</p>
              <p className="text-xs text-muted-foreground">This may take a few seconds</p>
            </div>
          )}

          {/* Empty State */}
          {!isLoading && !isGenerating && unusedSuggestions.length === 0 && (
            <div className="flex flex-col items-center justify-center py-12 gap-3">
              <Sparkles className="h-8 w-8 text-muted-foreground/50" />
              <p className="text-sm text-muted-foreground">No suggestions available</p>
              {canGenerate ? (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleGenerate}
                  disabled={isGenerating}
                >
                  <Sparkles className="h-4 w-4 mr-2" />
                  Generate Suggestions
                </Button>
              ) : (
                <p className="text-xs text-muted-foreground">
                  Organization limit reached
                </p>
              )}
            </div>
          )}

          {/* Suggestions List */}
          {!isLoading && unusedSuggestions.length > 0 && (
            <div className="flex flex-col gap-3 overflow-y-auto flex-1 -mx-2 px-2">
              {unusedSuggestions.map((suggestion) => (
                <button
                  key={suggestion.id}
                  onClick={() => handleSelectSuggestion(suggestion)}
                  disabled={usingSuggestionId === suggestion.id}
                  className={cn(
                    'flex flex-col gap-2 p-4 rounded-xl border transition-colors text-left',
                    'border-gray-200 dark:border-polar-700',
                    'hover:border-blue-300 dark:hover:border-blue-600',
                    'hover:bg-gray-50 dark:hover:bg-polar-800',
                    usingSuggestionId === suggestion.id && 'opacity-50 pointer-events-none'
                  )}
                >
                  <div className="flex items-center justify-between gap-2">
                    <h3 className="font-medium text-sm">{suggestion.title}</h3>
                    <div className="flex items-center gap-2 shrink-0">
                      <CategoryBadge category={suggestion.category} />
                      {usingSuggestionId === suggestion.id && (
                        <Loader2 className="h-4 w-4 animate-spin text-blue-500" />
                      )}
                    </div>
                  </div>
                  <p className="text-sm text-gray-600 dark:text-polar-400">
                    {suggestion.prompt}
                  </p>
                </button>
              ))}
            </div>
          )}

          {/* Footer */}
          <div className="flex flex-row items-center justify-between gap-x-4 pt-2 border-t border-gray-100 dark:border-polar-800">
            <p className="text-xs text-muted-foreground">
              {unusedSuggestions.length} suggestion{unusedSuggestions.length !== 1 ? 's' : ''} available
            </p>
            <Button
              type="button"
              variant="ghost"
              onClick={() => onOpenChange(false)}
            >
              Close
            </Button>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  )
}
