'use client'

import { useState, useRef, useCallback, useEffect } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { Button } from '@workspace/ui/components/button'
import { Badge } from '@workspace/ui/components/badge'
import { ArrowLeft, Cloud, CloudOff, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import { PlateEditor, type PlateEditorRef } from '@/components/editor/plate-editor'

// Mock content data - same as detail page
const mockContentData: Record<string, {
  id: string
  title: string
  type: 'blog' | 'article' | 'landing_page' | 'social'
  status: 'draft' | 'published' | 'scheduled' | 'archived'
  author: string
  publishedAt: Date | null
  createdAt: Date
  updatedAt: Date
  readTime: string
  content: string
}> = {
  'content-1': {
    id: 'content-1',
    title: 'The Complete Guide to AI Visibility: How to Get Your Brand Mentioned by ChatGPT, Perplexity, and Gemini',
    type: 'blog',
    status: 'published',
    author: 'Marketing Team',
    publishedAt: new Date('2026-01-15'),
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-15'),
    readTime: '12 min read',
    content: `# The Complete Guide to AI Visibility: How to Get Your Brand Mentioned by ChatGPT, Perplexity, and Gemini

## Introduction

In today's rapidly evolving digital landscape, a new frontier has emerged in brand visibility: AI-powered search engines and conversational assistants. As millions of users turn to ChatGPT, Perplexity, Google Gemini, and similar AI platforms to find answers, recommendations, and solutions, brands face both an unprecedented opportunity and a significant challenge.

The question is no longer just "How do we rank on Google?" but increasingly "How do we ensure AI systems recommend our brand when users ask for solutions?" This comprehensive guide will walk you through everything you need to know about AI visibility—what it is, why it matters, and most importantly, how to improve it.

## What Is AI Visibility?

AI visibility refers to how frequently and favorably your brand appears in responses generated by large language models (LLMs) and AI-powered search engines. Unlike traditional SEO, which focuses on ranking in search engine results pages (SERPs), AI visibility is about being part of the AI's "knowledge" and being recommended in conversational responses.

When a user asks ChatGPT "What's the best project management tool for remote teams?" or queries Perplexity about "top CRM platforms for small businesses," the AI draws from its training data and real-time information to formulate a response. Your AI visibility score measures how often your brand appears in these responses, in what context, and with what sentiment.

### The Three Pillars of AI Visibility

**1. Recognition**: Does the AI know your brand exists? This is the foundation—if you're not in the AI's knowledge base, you can't be recommended.

**2. Positioning**: When your brand is mentioned, how is it characterized? Are you positioned as a leader, an alternative, or merely one option among many?

**3. Sentiment**: What tone does the AI use when discussing your brand? Positive associations with quality, innovation, and reliability significantly impact recommendation likelihood.

## Why AI Visibility Matters Now

The shift toward AI-assisted decision-making represents one of the most significant changes in consumer behavior since the advent of mobile search. Consider these trends:

### Changing User Behavior

Users increasingly prefer conversational AI for product research because it provides synthesized, personalized answers rather than lists of links to evaluate. A recent study found that 67% of users who tried AI search continued using it as their primary research method.

### The Trust Factor

AI recommendations carry significant weight. When ChatGPT or Perplexity suggests a product or service, users perceive it as a vetted recommendation from an intelligent, unbiased source. This perceived objectivity makes AI mentions incredibly valuable for brand trust.

### First-Mover Advantage

The brands establishing strong AI visibility now will have a significant advantage as these platforms become more dominant. Like early SEO adopters who built lasting organic traffic, early AI visibility leaders are building brand associations that will be difficult for competitors to displace.

## Strategies to Improve Your AI Visibility

Now for the actionable part—here's how to systematically improve your brand's AI visibility across major platforms.

### 1. Content Strategy for AI Consumption

**Create Comprehensive, Authoritative Content**

AI models favor content that thoroughly addresses topics. Instead of thin content targeting specific keywords, develop in-depth resources that establish your expertise:

- Detailed guides and tutorials
- Original research and data
- Expert interviews and thought leadership
- Comprehensive product documentation

**Structure for AI Understanding**

Use clear headings, bullet points, and structured data to help AI systems understand and extract information:

- Implement FAQ schema markup
- Use clear, descriptive headings (H1, H2, H3)
- Include summary sections that directly answer common questions
- Add structured product information (specifications, pricing, features)

### 2. Build Authoritative Backlinks and Mentions

**Earn Coverage in Authoritative Publications**

AI models weight authoritative sources heavily. Pursue coverage in:

- Industry-leading publications and blogs
- Major news outlets (for significant announcements)
- Academic or research publications
- Government and institutional websites

### 3. Monitor and Measure AI Visibility

**Track Brand Mentions Across AI Platforms**

Regularly query major AI platforms with prompts relevant to your business:

- "What are the best [your category] tools?"
- "Compare [your brand] vs [competitor]"
- "What do people say about [your brand]?"

## Conclusion

AI visibility represents a fundamental shift in how consumers discover and evaluate brands. The organizations that recognize this shift and adapt their strategies accordingly will capture disproportionate value as AI becomes the primary interface for information and recommendations.

Start by auditing your current AI visibility across major platforms. Identify gaps in your content, authority, and brand consistency. Then systematically implement the strategies outlined in this guide, measuring progress and adjusting your approach based on results.

The brands that master AI visibility today will be the ones that thrive in tomorrow's AI-first world. The time to start is now.
`,
  },
  'content-2': {
    id: 'content-2',
    title: '10 Ways to Improve Your Brand Recognition in AI Search',
    type: 'article',
    status: 'draft',
    author: 'Content Writer',
    publishedAt: null,
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-24'),
    readTime: '8 min read',
    content: `# 10 Ways to Improve Your Brand Recognition in AI Search

## Draft Content

This article is currently being written. Check back soon for the full content.

### Outline:

1. Create comprehensive, authoritative content
2. Build quality backlinks from reputable sources
3. Maintain consistent brand information
4. Optimize for featured snippets
5. Develop strong Wikipedia presence
6. Encourage customer reviews
7. Publish original research
8. Engage in industry discussions
9. Keep content fresh and updated
10. Monitor and measure your AI visibility
`,
  },
}

export default function ContentEditPage() {
  const params = useParams()
  const router = useRouter()
  const projectId = params.id as string
  const contentId = params.contentId as string

  const editorRef = useRef<PlateEditorRef>(null)
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle')
  const [currentContent, setCurrentContent] = useState<string>('')
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null)

  const content = mockContentData[contentId]

  // Initialize content
  useEffect(() => {
    if (content) {
      setCurrentContent(content.content)
    }
  }, [content])

  // Auto-save handler
  const handleContentChange = useCallback((markdown: string) => {
    setCurrentContent(markdown)

    // Clear any existing timeout
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current)
    }

    // Set saving status
    setSaveStatus('saving')

    // Debounce the save (1.5 seconds after user stops typing)
    saveTimeoutRef.current = setTimeout(() => {
      // In a real app, this would save to the database
      // For now, just simulate a save
      setSaveStatus('saved')
      
      // Reset to idle after 2 seconds
      setTimeout(() => {
        setSaveStatus((current) => (current === 'saved' ? 'idle' : current))
      }, 2000)
    }, 1500)
  }, [])

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current)
      }
    }
  }, [])

  // Manual save
  const handleSave = useCallback(() => {
    setSaveStatus('saving')
    
    // Simulate save
    setTimeout(() => {
      setSaveStatus('saved')
      toast.success('Content saved successfully')
      
      setTimeout(() => {
        setSaveStatus((current) => (current === 'saved' ? 'idle' : current))
      }, 2000)
    }, 500)
  }, [])

  if (!content) {
    return (
      <div className="flex flex-1 flex-col items-center justify-center p-8">
        <p className="text-muted-foreground mb-4">Content not found</p>
        <Button variant="outline" onClick={() => router.back()}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Go Back
        </Button>
      </div>
    )
  }

  const getStatusBadge = (status: typeof content.status) => {
    switch (status) {
      case 'draft': return 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400'
      case 'published': return 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300'
      case 'scheduled': return 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300'
      case 'archived': return 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300'
    }
  }

  return (
    <div className="flex flex-1 flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border shrink-0">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={() => router.back()}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="flex items-center gap-2">
            <span className="font-medium text-sm truncate max-w-[300px]">{content.title}</span>
            <Badge className={getStatusBadge(content.status)}>
              {content.status.charAt(0).toUpperCase() + content.status.slice(1)}
            </Badge>
          </div>
        </div>
        <div className="flex items-center gap-3">
          {/* Auto-save status indicator */}
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            {saveStatus === 'saving' && (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                <span>Saving...</span>
              </>
            )}
            {saveStatus === 'saved' && (
              <>
                <Cloud className="h-3.5 w-3.5 text-green-600" />
                <span className="text-green-600">Saved</span>
              </>
            )}
            {saveStatus === 'error' && (
              <>
                <CloudOff className="h-3.5 w-3.5 text-red-500" />
                <span className="text-red-500">Save failed</span>
              </>
            )}
          </div>
          <Button variant="outline" size="sm" onClick={handleSave}>
            Save
          </Button>
        </div>
      </div>

      {/* Editor */}
      <div className="flex-1 min-h-0 overflow-hidden">
        <PlateEditor
          ref={editorRef}
          key={content.id}
          initialValue={content.content}
          containerVariant="default"
          variant="fullWidth"
          showSettings={false}
          className="h-full"
          onContentChange={handleContentChange}
        />
      </div>
    </div>
  )
}
